
services:
  - type: web
    name: smart-planner
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python smart_webhook.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: false
